In [1]:
import torch

# Calcular derivada

In [2]:
# Definimos una variable con gradiente
x = torch.tensor(3.0, requires_grad=True)

# Definimos una función escalar
y = x**2 + 2*x + 1

In [3]:
y.backward()

print(x.grad)  # dy/dx = 2x + 2 = 8

tensor(8.)


# Calcular derivadas parciales

In [4]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

f = x**2 * y + y**3

f.backward()

print(x.grad)  # ∂f/∂x = 2xy = 2*2*3 = 12
print(y.grad)  # ∂f/∂y = x² + 3y² = 4 + 27 = 31


tensor(12.)
tensor(31.)


# grad

In [29]:
import torch
import numpy as np

x1 = torch.tensor([[3.0 , 5.0, 2.0]], requires_grad=True)
x2 = torch.tensor([[7.0 , 1.0, 3.0]], requires_grad=True)
x = torch.concat([x1, x2])
print(f"{x=}")
y1 = x**2 + 2*x
y2 = 5*x**2

grad_y1_x = torch.autograd.grad(y1, x, grad_outputs=torch.ones_like(y1))
grad_y2_x = torch.autograd.grad(y2, x, grad_outputs=torch.ones_like(y2))
print(grad_y1_x)  # (tensor(8.),)
print(grad_y2_x)  # (tensor(8.),)


x=tensor([[3., 5., 2.],
        [7., 1., 3.]], grad_fn=<CatBackward0>)
(tensor([[ 8., 12.,  6.],
        [16.,  4.,  8.]]),)
(tensor([[30., 50., 20.],
        [70., 10., 30.]]),)


In [50]:
x1 = np.arange(2,50,12)[:,None]
x2 = np.arange(4,50,12)[:,None]

x1 = torch.from_numpy(x1).to(torch.float32).requires_grad_(True)
x2 = torch.from_numpy(x2).to(torch.float32).requires_grad_(True)

x = torch.concat([x1, x2], axis=1)

y1 = x**2 + 2*x

grad_y1_x = torch.autograd.grad(y1, x, grad_outputs=torch.ones_like(y1))
print(grad_y1_x[0])  # (tensor(8.),)


tensor([[ 6., 10.],
        [30., 34.],
        [54., 58.],
        [78., 82.]])


In [17]:
import torch

x = torch.randn(2, 3, requires_grad=True)  # Tensor 2x3
y1 = x**2 + 2*x
y2 = 5*x

grad_y1_x = torch.autograd.grad(
    outputs=y1,
    inputs=x,
    grad_outputs=torch.ones_like(y1),
    create_graph=True
)[0]

grad_y2_x = torch.autograd.grad(
    outputs=y2,
    inputs=x,
    grad_outputs=torch.ones_like(y2),
    create_graph=True
)[0]

print("x =\n", x)
print("y1 = x^2 + 2x =\n", y1)
print("y2 = 5x =\n", y1)
print("∂y1/∂x =\n", grad_y1_x)
print("∂y2/∂x =\n", grad_y2_x)


x =
 tensor([[ 1.7383,  2.2778, -1.8181],
        [-0.3021, -0.1142,  1.2707]], requires_grad=True)
y1 = x^2 + 2x =
 tensor([[ 6.4984,  9.7438, -0.3308],
        [-0.5129, -0.2154,  4.1562]], grad_fn=<AddBackward0>)
y2 = 5x =
 tensor([[ 6.4984,  9.7438, -0.3308],
        [-0.5129, -0.2154,  4.1562]], grad_fn=<AddBackward0>)
∂y1/∂x =
 tensor([[ 5.4766,  6.5556, -1.6362],
        [ 1.3959,  1.7716,  4.5415]], grad_fn=<AddBackward0>)
∂y2/∂x =
 tensor([[5., 5., 5.],
        [5., 5., 5.]])
